kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: ${NAMESPACE}
  name: test-pvc
  annotations:
    dotmeshNamespace: admin
    dotmeshName: ${NAMESPACE}
spec:
  storageClassName: dotmesh
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi